# ==========================================================================
# Build system
# ==========================================================================

CFLAGS += $(call cc-option,-arch armv7,-march=armv7)
LDFLAGS += $(call cc-option,-arch armv7,-march=armv7)
